### ISSUE TITLE
Adding mutually exclusive arguments

### ISSUE THREAD

**Issue by MangaD** [p-ranav/argparse#289] opened 2023-10-12 14:43 UTC
It would be nice to have an option to add mutually exclusive arguments, as exists in the Python argparse library: https://stackoverflow.com/questions/7869345/how-to-make-python-argparse-mutually-exclusive-group-arguments-without-prefix

**Comment by p-ranav** [comment] 2023-10-27 22:07
Duplicate of #221

**Closed by p-ranav** 2023-10-27 22:07 UTC
